### ISSUE TITLE
Add husky support

### ISSUE THREAD

**Issue by lodi-g** [altern-intra/intra-api#9]
I think [husky](https://github.com/typicode/husky) would be appropriate to add github hooks such as prepush & precommit.
Those hooks would run `npm run lint` and `npm run test` before allowing users to commit / push.

**Comment by Wats0ns** [comment]
Yup, this would be truly useful. Wanna do it @lodi-g ?

**Comment by lodi-g** [comment]
Sure, I'll do that.

**Comment by lodi-g** [comment]
This issue was addressed in the PR #10 😉

**Comment by Wats0ns** [comment]
Thanks @lodi-g
